// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameJob = "job"

// Job mapped from table <job>
type Job struct {
	ID       int32     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name     string    `gorm:"column:name;type:varchar(50);not null" json:"name"`
	Status   int32     `gorm:"column:status;type:smallint(6);not null" json:"status"`
	Command  string    `gorm:"column:command;type:varchar(100);not null" json:"command"`
	CronExpr string    `gorm:"column:cronExpr;type:varchar(100);not null" json:"cronExpr"`
	PlanTime time.Time `gorm:"column:planTime;type:datetime(6);not null" json:"planTime"`
	NextTime time.Time `gorm:"column:nextTime;type:datetime(6);not null" json:"nextTime"`
	Created  time.Time `gorm:"column:created;type:datetime(6);not null;default:current_timestamp(6)" json:"created"`
	Updated  time.Time `gorm:"column:updated;type:datetime(6);not null;default:current_timestamp(6)" json:"updated"`
}

// TableName Job's table name
func (*Job) TableName() string {
	return TableNameJob
}
