POST http://{{host}}:{{port}}/job/create
Content-Type: application/json

{
  "status": 2,
  "name": "hello1",
  "command": "echo hello",
  "cronExpr": "*/5 * * * * * * *"
}

### 删除
POST http://{{host}}:{{port}}/job/delete
Content-Type: application/json

{
  "id": 8
}


### 查询列表
GET http://{{host}}:{{port}}/job/list?offset=0&limit=10

### 查询详情
GET http://{{host}}:{{port}}/job/detail/1